### ISSUE TITLE
Failing pipeline.

### ISSUE THREAD

**Issue by khoroshevskyi** [databio/bedboss#79]
Error:
```
│ /sfs/qumulo/qhome/bnt4me/venv/main/lib/python3.11/site-packages/pipestat/pip │
│ estat.py:105 in inner                                                        │
│                                                                              │
│    102 │   def inner(self, *args, **kwargs):                                 │
│    103 │   │   if not self.backend:                                          │
│    104 │   │   │   raise NoBackendSpecifiedError                             │
│ ❱  105 │   │   return func(self, *args, **kwargs)                            │
│    106 │                                                                     │
│    107 │   return inner                                                      │
│    108                                                                       │
│                                                                              │
│ /sfs/qumulo/qhome/bnt4me/venv/main/lib/python3.11/site-packages/pipestat/pip │
│ estat.py:906 in set_status                                                   │
│                                                                              │
│    903 │   │   │   pipeline status for                                       │
│    904 │   │   """                                                           │
│    905 │   │   r_id = record_identifier or self.record_identifier            │
│ ❱  906 │   │   self.backend.set_status(status_identifier, r_id)              │
│    907 │                                                                     │
│    908 │   @require_backend                                                  │
│    909 │   def link(self, link_dir) -> Union[str, None]:                     │
│                                                                              │
│ /sfs/qumulo/qhome/bnt4me/venv/main/lib/python3.11/site-packages/pipestat/bac │
│ kends/file_backend/filebackend.py:669 in set_status                          │
│                                                                              │
│   666 │   │                                                                  │
│   667 │   │   if prev_status is not None:                                    │
│   668 │   │   │   prev_flag_path = self.get_status_flag_path(prev_status, re │
│ ❱ 669 │   │   │   os.remove(prev_flag_path)                                  │
│   670 │   │   flag_path = self.get_status_flag_path(status_identifier, recor │
│   671 │   │   create_lock(flag_path)                                         │
│   672 │   │   with open(flag_path, "w") as f:                                │
╰──────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: 
'/project/shefflab/brickyard/datasets_processed/bedmaker_logs/default_pipeline_n
ame_DEFAULT_SAMPLE_NAME_completed.flag'

### Pipeline failed at:  (09-26 14:47:38) elapsed: 0.0 _TIME_

Total time: 0:00:01
Failure reason: Pipeline failure. See details above.
Exception ignored in atexit callback: <bound method PipelineManager._exit_handler of <pypiper.manager.PipelineManager object at 0x1458836a7f10>>
Traceback (most recent call last):
  File "/sfs/qumulo/qhome/bnt4me/venv/main/lib/python3.11/site-packages/pypiper/manager.py", line 2165, in _exit_handler
    self.fail_pipeline(Exception("Pipeline failure. See details above."))
  File "/sfs/qumulo/qhome/bnt4me/venv/main/lib/python3.11/site-packages/pypiper/manager.py", line 2009, in fail_pipeline
    raise exc
Exception: Pipeline failure. See details above.

```

Solution for now: change project name in pipeline pypiper

**Comment by khoroshevskyi** [comment]
Fixed in previous release by changing pipeline name, and fixed bug in pypiper
